steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker build --no-cache \
          -t "$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA" \
          --build-arg _AUTH_SECRET="$_AUTH_SECRET" \
          --build-arg _AUTH_DISCORD_ID="$_AUTH_DISCORD_ID" \
          --build-arg _AUTH_DISCORD_SECRET="$_AUTH_DISCORD_SECRET" \
          --build-arg _DATABASE_URL="$_DATABASE_URL" \
          --build-arg _NEXT_PUBLIC_EMAILJS_SERVICE_ID="$_NEXT_PUBLIC_EMAILJS_SERVICE_ID" \
          --build-arg _NEXT_PUBLIC_EMAILJS_TEMPLATE_ID="$_NEXT_PUBLIC_EMAILJS_TEMPLATE_ID" \
          --build-arg _NEXT_PUBLIC_EMAILJS_PERSONAL_TOKEN="$_NEXT_PUBLIC_EMAILJS_PERSONAL_TOKEN" \
          -f Dockerfile .
    id: Build
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_PROJECT_ID: nexelon-469619
  _PLATFORM: managed
  _SERVICE_NAME: samuel-hrotik
  REPO_NAME: samuel-hrotik
  _DEPLOY_REGION: europe-west1
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _TRIGGER_ID: d45f96ec-8d6e-45db-a2b0-67a531f6cacb
  _AR_REPOSITORY: cloud-run-source-deploy
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - samuel-hrotik
